name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  packages: write

jobs:
  build:
    strategy:
      matrix:
        variants:
          - tag: ""
          - tag: "-fips"
            patches: fips.patch
            build-args: |
              BUILD_IMAGE=ghcr.io/goauthentik/fips-debian:bookworm-slim-fips
              RUN_IMAGE=ghcr.io/goauthentik/fips-debian:bookworm-slim-fips
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - id: tag
        run: |
          cd guacamole-server
          guac_tag=$(git describe --tags)
          echo "tag=$guac_tag"
          echo "tag=$guac_tag" >> "$GITHUB_OUTPUT"
      - name: Apply patches
        run: |
          git apply ${{ matrix.variants.patches }} --allow-empty
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5.3.0
        with:
          tags: |
            ghcr.io/beryju/guacd:${{ steps.tag.outputs.tag }}
          push: ${{ github.ref == 'refs/heads/main' }}
          platforms: linux/amd64,linux/arm64
          context: .
      - uses: docker/build-push-action@v5.3.0
        with:
          tags: |
            ghcr.io/beryju/guacd:${{ steps.tag.outputs.tag }}${{ matrix.variants.tag }}
          push: ${{ github.ref == 'refs/heads/main' }}
          platforms: linux/amd64,linux/arm64
          context: .
          build-args: ${{ matrix.variants.build-args }}
